# This is a configuration file for DaVinci CLI.
# The following sections define the configuration for various components of DaVinci CLI.
[cli]
# The CLI section contains settings related to the command-line interface.
command = 'dav'
# The command to invoke DaVinci CLI.
version = '1.0.0'
# The version of DaVinci CLI.
description = 'DaVinci CLI - A command-line interface for DaVinci.'
[commands]
# The commands section defines the available commands in DaVinci CLI.
